name: NIP Rent

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Test with pytest
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6

    - name: Install UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --dev

    - name: Run tests
      run: uv run pytest tests -v 

    - name: Run linter (code/src)
      run: uv run ruff check src --exit-zero

    - name: Run linter (main_demo.py)
      run: uv run ruff check main_demo.py --exit-zero
    - name: Generate Docs
      run: uv run pdoc src/ -o ./docs-output 

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs-output'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
